# Generated by Django 4.2.7 on 2023-11-14 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_remove_tratamiento_fecha_creacion_tratamiento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobremi',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
