# Generated by Django 4.2.7 on 2023-11-16 02:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_sobremi_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
